import type { EventCard } from "@/engine/types";
import { CHARACTERS, ITEMS, LOCATIONS } from "./module";

export const blindDateEvents: EventCard[] = [
  {
    id: "greet-partner",
    intentType: "talk",
    targetId: CHARACTERS.PARTNER,
    locationId: LOCATIONS.TABLE,
    effects: { clues: 1, closeness: "有动静" },
    templateKeys: ["greet-partner-1", "greet-partner-2"],
  },
  {
    id: "greet-partner-repeat",
    intentType: "talk",
    targetId: CHARACTERS.PARTNER,
    locationId: LOCATIONS.TABLE,
    repeatable: true,
    effects: {},
    templateKeys: ["greet-partner-repeat-1"],
  },
  {
    id: "toast-wine",
    intentType: "use",
    targetId: ITEMS.WINE,
    locationId: LOCATIONS.TABLE,
    effects: { clues: 1, setFlags: ["toasted"] },
    templateKeys: ["toast-wine-1", "toast-wine-2"],
  },
  {
    id: "toast-wine-repeat",
    intentType: "use",
    targetId: ITEMS.WINE,
    locationId: LOCATIONS.TABLE,
    requiresFlags: ["toasted"],
    repeatable: true,
    effects: {},
    templateKeys: ["toast-wine-repeat-1"],
  },
  {
    id: "chat-topic",
    intentType: "use",
    targetId: ITEMS.TOPIC,
    locationId: LOCATIONS.TABLE,
    requiresFlags: ["toasted"],
    effects: { clues: 1, closeness: "很近", setFlags: ["topic_ok"] },
    templateKeys: ["chat-topic-1", "chat-topic-2"],
  },
  {
    id: "chat-topic-repeat",
    intentType: "use",
    targetId: ITEMS.TOPIC,
    locationId: LOCATIONS.TABLE,
    requiresFlags: ["topic_ok"],
    repeatable: true,
    effects: {},
    templateKeys: ["chat-topic-repeat-1"],
  },
  {
    id: "chat-topic-too-early",
    intentType: "use",
    targetId: ITEMS.TOPIC,
    locationId: LOCATIONS.TABLE,
    repeatable: true,
    effects: {},
    templateKeys: ["chat-topic-too-early-1"],
  },
  {
    id: "calm-matchmaker",
    intentType: "talk",
    targetId: CHARACTERS.MATCHMAKER,
    locationId: LOCATIONS.TABLE,
    requiresFlags: ["topic_ok"],
    effects: { clues: 1, closeness: "已找到", setFlags: ["can_exit"] },
    templateKeys: ["calm-matchmaker-1", "calm-matchmaker-2"],
  },
  {
    id: "calm-matchmaker-repeat",
    intentType: "talk",
    targetId: CHARACTERS.MATCHMAKER,
    locationId: LOCATIONS.TABLE,
    requiresFlags: ["can_exit"],
    repeatable: true,
    effects: {},
    templateKeys: ["calm-matchmaker-repeat-1"],
  },
  {
    id: "calm-matchmaker-too-early",
    intentType: "talk",
    targetId: CHARACTERS.MATCHMAKER,
    locationId: LOCATIONS.TABLE,
    repeatable: true,
    effects: {},
    templateKeys: ["calm-matchmaker-too-early-1"],
  },
  {
    id: "observe-table",
    intentType: "search",
    locationId: LOCATIONS.TABLE,
    repeatable: true,
    effects: {},
    templateKeys: ["observe-table-1", "observe-table-2"],
  },
  {
    id: "call-waiter",
    intentType: "call",
    locationId: LOCATIONS.TABLE,
    repeatable: true,
    effects: {},
    templateKeys: ["call-waiter-1"],
  },
];
