import type { EventCard } from "@/engine/types";
import { CHARACTERS, ITEMS, LOCATIONS } from "./module";

export const plantWeekEvents: EventCard[] = [
  {
    id: "water-first",
    intentType: "use",
    targetId: ITEMS.WATER,
    locationId: LOCATIONS.LIVING,
    effects: { clues: 1, setFlags: ["watered"] },
    templateKeys: ["water-first-1", "water-first-2"],
  },
  {
    id: "water-again",
    intentType: "use",
    targetId: ITEMS.WATER,
    locationId: LOCATIONS.LIVING,
    requiresFlags: ["fertilized"],
    effects: { closeness: "很近", setFlags: ["watered_again"] },
    templateKeys: ["water-again-1", "water-again-2"],
  },
  {
    id: "water-repeat",
    intentType: "use",
    targetId: ITEMS.WATER,
    locationId: LOCATIONS.LIVING,
    requiresFlags: ["watered_again"],
    repeatable: true,
    effects: {},
    templateKeys: ["water-repeat-1"],
  },
  {
    id: "water-on-balcony",
    intentType: "use",
    targetId: ITEMS.WATER,
    locationId: LOCATIONS.BALCONY,
    repeatable: true,
    effects: {},
    templateKeys: ["water-on-balcony-1"],
  },
  {
    id: "sunbathe",
    intentType: "search",
    locationId: LOCATIONS.BALCONY,
    requiresFlags: ["watered"],
    effects: { closeness: "有动静", setFlags: ["sunned"] },
    templateKeys: ["sunbathe-1", "sunbathe-2"],
  },
  {
    id: "sunbathe-repeat",
    intentType: "search",
    locationId: LOCATIONS.BALCONY,
    requiresFlags: ["sunned"],
    repeatable: true,
    effects: {},
    templateKeys: ["sunbathe-repeat-1"],
  },
  {
    id: "sunbathe-too-early",
    intentType: "search",
    locationId: LOCATIONS.BALCONY,
    repeatable: true,
    effects: {},
    templateKeys: ["sunbathe-too-early-1"],
  },
  {
    id: "fertilize",
    intentType: "use",
    targetId: ITEMS.FERTILIZER,
    locationId: LOCATIONS.BALCONY,
    requiresFlags: ["sunned"],
    effects: { clues: 1, setFlags: ["fertilized"] },
    templateKeys: ["fertilize-1", "fertilize-2"],
  },
  {
    id: "fertilize-repeat",
    intentType: "use",
    targetId: ITEMS.FERTILIZER,
    locationId: LOCATIONS.BALCONY,
    requiresFlags: ["fertilized"],
    repeatable: true,
    effects: {},
    templateKeys: ["fertilize-repeat-1"],
  },
  {
    id: "fertilize-too-early",
    intentType: "use",
    targetId: ITEMS.FERTILIZER,
    locationId: LOCATIONS.BALCONY,
    repeatable: true,
    effects: {},
    templateKeys: ["fertilize-too-early-1"],
  },
  {
    id: "fertilize-wrong-place",
    intentType: "use",
    targetId: ITEMS.FERTILIZER,
    locationId: LOCATIONS.LIVING,
    repeatable: true,
    effects: {},
    templateKeys: ["fertilize-wrong-place-1"],
  },
  {
    id: "shade",
    intentType: "use",
    targetId: ITEMS.SHADE,
    locationId: LOCATIONS.BALCONY,
    requiresFlags: ["sunned"],
    effects: { setFlags: ["shaded"] },
    templateKeys: ["shade-1", "shade-2"],
  },
  {
    id: "shade-repeat",
    intentType: "use",
    targetId: ITEMS.SHADE,
    locationId: LOCATIONS.BALCONY,
    requiresFlags: ["shaded"],
    repeatable: true,
    effects: {},
    templateKeys: ["shade-repeat-1"],
  },
  {
    id: "check-health",
    intentType: "talk",
    targetId: CHARACTERS.PLANT,
    locationId: LOCATIONS.LIVING,
    requiresFlags: ["watered_again"],
    effects: { closeness: "已找到", setFlags: ["healthy"] },
    templateKeys: ["check-health-1", "check-health-2"],
  },
  {
    id: "check-health-repeat",
    intentType: "talk",
    targetId: CHARACTERS.PLANT,
    locationId: LOCATIONS.LIVING,
    requiresFlags: ["healthy"],
    repeatable: true,
    effects: {},
    templateKeys: ["check-health-repeat-1"],
  },
  {
    id: "check-health-too-early",
    intentType: "talk",
    targetId: CHARACTERS.PLANT,
    locationId: LOCATIONS.LIVING,
    repeatable: true,
    effects: {},
    templateKeys: ["check-health-too-early-1"],
  },
  {
    id: "slack-off",
    intentType: "search",
    locationId: LOCATIONS.LIVING,
    repeatable: true,
    effects: {},
    templateKeys: ["slack-off-1", "slack-off-2"],
  },
];
