import type { EventCard } from "@/engine/types";
import { CHARACTERS, ITEMS, LOCATIONS } from "./module";

export const chunyunEvents: EventCard[] = [
  {
    id: "refresh-page",
    intentType: "use",
    targetId: ITEMS.REFRESH,
    locationId: LOCATIONS.DESK,
    effects: { clues: 1, closeness: "有动静", setFlags: ["refreshed"] },
    templateKeys: ["refresh-page-1", "refresh-page-2"],
  },
  {
    id: "refresh-page-repeat",
    intentType: "use",
    targetId: ITEMS.REFRESH,
    locationId: LOCATIONS.DESK,
    requiresFlags: ["refreshed"],
    repeatable: true,
    effects: {},
    templateKeys: ["refresh-page-repeat-1"],
  },
  {
    id: "ask-family",
    intentType: "talk",
    targetId: CHARACTERS.FAMILY,
    locationId: LOCATIONS.DESK,
    requiresFlags: ["refreshed"],
    effects: { clues: 1, setFlags: ["family_help"] },
    templateKeys: ["ask-family-1", "ask-family-2"],
  },
  {
    id: "ask-family-repeat",
    intentType: "talk",
    targetId: CHARACTERS.FAMILY,
    locationId: LOCATIONS.DESK,
    requiresFlags: ["family_help"],
    repeatable: true,
    effects: {},
    templateKeys: ["ask-family-repeat-1"],
  },
  {
    id: "ask-family-too-early",
    intentType: "talk",
    targetId: CHARACTERS.FAMILY,
    locationId: LOCATIONS.DESK,
    repeatable: true,
    effects: {},
    templateKeys: ["ask-family-too-early-1"],
  },
  {
    id: "change-train",
    intentType: "use",
    targetId: ITEMS.TRAIN,
    locationId: LOCATIONS.DESK,
    requiresFlags: ["family_help"],
    effects: { clues: 1, closeness: "很近", setFlags: ["alt_train"] },
    templateKeys: ["change-train-1", "change-train-2"],
  },
  {
    id: "change-train-repeat",
    intentType: "use",
    targetId: ITEMS.TRAIN,
    locationId: LOCATIONS.DESK,
    requiresFlags: ["alt_train"],
    repeatable: true,
    effects: {},
    templateKeys: ["change-train-repeat-1"],
  },
  {
    id: "change-train-too-early",
    intentType: "use",
    targetId: ITEMS.TRAIN,
    locationId: LOCATIONS.DESK,
    repeatable: true,
    effects: {},
    templateKeys: ["change-train-too-early-1"],
  },
  {
    id: "grab-ticket",
    intentType: "use",
    targetId: ITEMS.TICKET,
    locationId: LOCATIONS.DESK,
    requiresFlags: ["alt_train"],
    effects: { closeness: "已找到", setFlags: ["ticket_locked"] },
    templateKeys: ["grab-ticket-1", "grab-ticket-2"],
  },
  {
    id: "grab-ticket-repeat",
    intentType: "use",
    targetId: ITEMS.TICKET,
    locationId: LOCATIONS.DESK,
    requiresFlags: ["ticket_locked"],
    repeatable: true,
    effects: {},
    templateKeys: ["grab-ticket-repeat-1"],
  },
  {
    id: "grab-ticket-too-early",
    intentType: "use",
    targetId: ITEMS.TICKET,
    locationId: LOCATIONS.DESK,
    repeatable: true,
    effects: {},
    templateKeys: ["grab-ticket-too-early-1"],
  },
  {
    id: "stare-screen",
    intentType: "search",
    locationId: LOCATIONS.DESK,
    repeatable: true,
    effects: {},
    templateKeys: ["stare-screen-1", "stare-screen-2"],
  },
];
