// 电梯事件卡:单地点。通关靠安抚→报警→检查→对讲→出梯。
import type { EventCard } from "@/engine/types";
import { CHARACTERS, ITEMS, LOCATIONS } from "./module";

export const elevatorEvents: EventCard[] = [
  {
    id: "calm-grandma",
    intentType: "talk",
    targetId: CHARACTERS.GRANDMA,
    locationId: LOCATIONS.CABIN,
    effects: { clues: 1, closeness: "有动静" },
    templateKeys: ["calm-grandma-1", "calm-grandma-2"],
  },
  {
    id: "calm-grandma-repeat",
    intentType: "talk",
    targetId: CHARACTERS.GRANDMA,
    locationId: LOCATIONS.CABIN,
    repeatable: true,
    effects: {},
    templateKeys: ["calm-grandma-repeat-1"],
  },
  {
    id: "press-alarm",
    intentType: "use",
    targetId: ITEMS.ALARM,
    locationId: LOCATIONS.CABIN,
    effects: { clues: 1, setFlags: ["alarm_on"] },
    templateKeys: ["press-alarm-1", "press-alarm-2"],
  },
  {
    id: "press-alarm-repeat",
    intentType: "use",
    targetId: ITEMS.ALARM,
    locationId: LOCATIONS.CABIN,
    requiresFlags: ["alarm_on"],
    repeatable: true,
    effects: {},
    templateKeys: ["press-alarm-repeat-1"],
  },
  {
    id: "ask-office",
    intentType: "talk",
    targetId: CHARACTERS.OFFICE,
    locationId: LOCATIONS.CABIN,
    effects: { clues: 1 },
    templateKeys: ["ask-office-1", "ask-office-2"],
  },
  {
    id: "ask-office-repeat",
    intentType: "talk",
    targetId: CHARACTERS.OFFICE,
    locationId: LOCATIONS.CABIN,
    repeatable: true,
    effects: {},
    templateKeys: ["ask-office-repeat-1"],
  },
  {
    id: "ask-rider",
    intentType: "talk",
    targetId: CHARACTERS.RIDER,
    locationId: LOCATIONS.CABIN,
    effects: { clues: 1 },
    templateKeys: ["ask-rider-1", "ask-rider-2"],
  },
  {
    id: "ask-rider-repeat",
    intentType: "talk",
    targetId: CHARACTERS.RIDER,
    locationId: LOCATIONS.CABIN,
    repeatable: true,
    effects: {},
    templateKeys: ["ask-rider-repeat-1"],
  },
  {
    id: "check-panel",
    intentType: "search",
    locationId: LOCATIONS.CABIN,
    requiresFlags: ["alarm_on"],
    effects: { clues: 1, closeness: "很近", setFlags: ["panel_checked"] },
    templateKeys: ["check-panel-1", "check-panel-2"],
  },
  // 面板已打开后的重复搜索:必须排在「太早」兜底卡之前
  {
    id: "check-panel-repeat",
    intentType: "search",
    locationId: LOCATIONS.CABIN,
    requiresFlags: ["panel_checked"],
    repeatable: true,
    effects: {},
    templateKeys: ["check-panel-repeat-1"],
  },
  {
    id: "check-panel-too-early",
    intentType: "search",
    locationId: LOCATIONS.CABIN,
    effects: {},
    repeatable: true,
    templateKeys: ["check-panel-too-early-1"],
  },
  {
    id: "use-intercom",
    intentType: "use",
    targetId: ITEMS.INTERCOM,
    locationId: LOCATIONS.CABIN,
    requiresFlags: ["alarm_on", "panel_checked"],
    effects: { closeness: "已找到", setFlags: ["rescue_coming"] },
    templateKeys: ["use-intercom-1", "use-intercom-2"],
  },
  {
    id: "call-outside",
    intentType: "call",
    locationId: LOCATIONS.CABIN,
    repeatable: true,
    effects: {},
    templateKeys: ["call-outside-1", "call-outside-2"],
  },
];
